- hosts: masters
  become: yes
  tasks:
    - name: initialize K8S cluster
      shell: kubeadm init --pod-network-cidr=192.168.100.0/24 --apiserver-advertise-address=10.0.0.72

    - name: create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user kube config
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        mode: '0644'

    - pause: seconds=30     
     
    - name: install Pod network
      become_user: root
      become_method: sudo
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/v3.21/manifests/calico.yaml
                                                          